(define (problem shrdlu)
  (:domain shrdlu)
  (:objects a b c d e f g h i j k l m f1 f2 f3 f4 f5 f6 f7 f8 f9 f10)
  (:init
    ;; All objects are smaller than the floor tiles.
    (smaller a f1)
    (smaller a f2)
    (smaller a f3)
    (smaller a f4)
    (smaller a f5)
    (smaller a f6)
    (smaller a f7)
    (smaller a f8)
    (smaller a f9)
    (smaller a f10)
    (smaller b f1)
    (smaller b f2)
    (smaller b f3)
    (smaller b f4)
    (smaller b f5)
    (smaller b f6)
    (smaller b f7)
    (smaller b f8)
    (smaller b f9)
    (smaller b f10)
    (smaller c f1)
    (smaller c f2)
    (smaller c f3)
    (smaller c f4)
    (smaller c f5)
    (smaller c f6)
    (smaller c f7)
    (smaller c f8)
    (smaller c f9)
    (smaller c f10)
    (smaller d f1)
    (smaller d f2)
    (smaller d f3)
    (smaller d f4)
    (smaller d f5)
    (smaller d f6)
    (smaller d f7)
    (smaller d f8)
    (smaller d f9)
    (smaller d f10)
    (smaller e f1)
    (smaller e f2)
    (smaller e f3)
    (smaller e f4)
    (smaller e f5)
    (smaller e f6)
    (smaller e f7)
    (smaller e f8)
    (smaller e f9)
    (smaller e f10)
    (smaller f f1)
    (smaller f f2)
    (smaller f f3)
    (smaller f f4)
    (smaller f f5)
    (smaller f f6)
    (smaller f f7)
    (smaller f f8)
    (smaller f f9)
    (smaller f f10)
    (smaller g f1)
    (smaller g f2)
    (smaller g f3)
    (smaller g f4)
    (smaller g f5)
    (smaller g f6)
    (smaller g f7)
    (smaller g f8)
    (smaller g f9)
    (smaller g f10)
    (smaller h f1)
    (smaller h f2)
    (smaller h f3)
    (smaller h f4)
    (smaller h f5)
    (smaller h f6)
    (smaller h f7)
    (smaller h f8)
    (smaller h f9)
    (smaller h f10)
    (smaller i f1)
    (smaller i f2)
    (smaller i f3)
    (smaller i f4)
    (smaller i f5)
    (smaller i f6)
    (smaller i f7)
    (smaller i f8)
    (smaller i f9)
    (smaller i f10)
    (smaller j f1)
    (smaller j f2)
    (smaller j f3)
    (smaller j f4)
    (smaller j f5)
    (smaller j f6)
    (smaller j f7)
    (smaller j f8)
    (smaller j f9)
    (smaller j f10)
    (smaller k f1)
    (smaller k f2)
    (smaller k f3)
    (smaller k f4)
    (smaller k f5)
    (smaller k f6)
    (smaller k f7)
    (smaller k f8)
    (smaller k f9)
    (smaller k f10)
    (smaller l f1)
    (smaller l f2)
    (smaller l f3)
    (smaller l f4)
    (smaller l f5)
    (smaller l f6)
    (smaller l f7)
    (smaller l f8)
    (smaller l f9)
    (smaller l f10)
    (smaller m f1)
    (smaller m f2)
    (smaller m f3)
    (smaller m f4)
    (smaller m f5)
    (smaller m f6)
    (smaller m f7)
    (smaller m f8)
    (smaller m f9)
    (smaller m f10)
    
    ;; Some objects are smaller than others.
    (smaller a c)
    (smaller a d)
    (smaller a e)
    (smaller a f)
    (smaller a g)
    (smaller a h)
    (smaller a i)
    (smaller a j)
    (smaller a l)
    (smaller a m)
    (smaller c d)
    (smaller c e)
    (smaller c j)
    (smaller e c)
    (smaller e d)
    (smaller e j)
    (smaller f c)
    (smaller f d)
    (smaller f e)
    (smaller f g)
    (smaller f h)
    (smaller f i)
    (smaller f j)
    (smaller f l)
    (smaller f m)
    (smaller g c)
    (smaller g d)
    (smaller g e)
    (smaller g f)
    (smaller g h)
    (smaller g i)
    (smaller g j)
    (smaller g l)
    (smaller g m)
    (smaller h c)
    (smaller h d)
    (smaller h e)
    (smaller h f)
    (smaller h g)
    (smaller h i)
    (smaller h j)
    (smaller h l)
    (smaller h m)
    (smaller j c)
    (smaller j d)
    (smaller j e)
    (smaller l c)
    (smaller l d)
    (smaller l e)
    (smaller l i)
    (smaller l j)
    (smaller l m)
    
    ;; Some objects are clear.
    (clear f1)
    (clear b)
    (clear d)
    (clear f4)
    (clear i)
    (clear f6)
    (clear f7)
    (clear k)
    (clear f9)
    (clear m)
    
    ;; Some object are boxes.
    (box e)
    (box j)
    (box l)
    
    ;; Objects which are _on_ other objects.
    (on b a)
    (on a f2)
    (on d c)
    (on c f3)
    (on i h)
    (on h g)
    (on g f)
    (on f e)
    (on e f5)
    (on k j)
    (on j f8)
    (on m l)
    (on l f10)
    
    ;; Objects which are _in_ other objects.
    (in e e)
    (in f e)
    (in g e)
    (in h e)
    (in i e)
    (in j j)
    (in k j)
    (in l l)
    (in m l)
    (in-any e)
    (in-any f)
    (in-any g)
    (in-any h)
    (in-any i)
    (in-any j)
    (in-any k)
    (in-any l)
    (in-any m)
    
    ;; Objects are above floor tiles.
    (above f1 f1)
    (above f2 f2)
    (above a f2)
    (above b f2)
    (above f3 f3)
    (above c f3)
    (above d f3)
    (above f4 f4)
    (above f5 f5)
    (above e f5)
    (above f f5)
    (above g f5)
    (above h f5)
    (above i f5)
    (above f6 f6)
    (above f7 f7)
    (above f8 f8)
    (above j f8)
    (above k f8)
    (above f9 f9)
    (above f10 f10)
    (above l f10)
    (above m f10)
  )
  (:goal
    (and
      (on b a)
      (on a f2)
      (on d c)
      (on c f3)
      (on i h)
      (on h g)
      (on g f)
      (on f e)
      (on e f5)
      (on k j)
      (on j f8)
      (on m l)
      (on l f10)
      
      (in e e)
      (in f e)
      (in g e)
      (in h e)
      (in i e)
      (in j j)
      (in k j)
      (in l l)
      (in m l)
      (in-any e)
      (in-any f)
      (in-any g)
      (in-any h)
      (in-any i)
      (in-any j)
      (in-any k)
      (in-any l)
      (in-any m)
    )
  )
)
